import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Editorial Policy | Gita Guidance",
  description: "Our guidelines and commitments for providing authentic spiritual content.",
};

export default function EditorialPolicyPage() {
  return (
    <main className="flex-1 max-w-4xl mx-auto w-full p-4 md:p-8 mt-12 mb-20 relative z-10">
      <h1 className="font-serif text-4xl md:text-5xl font-bold mb-8 text-primary">Editorial Policy</h1>
      
      <div className="space-y-8 text-foreground/80 leading-loose text-lg">
        <section>
          <h2 className="font-serif text-2xl font-bold mb-4 text-foreground">Our Commitment to Authenticity</h2>
          <p>
            At Gita Guidance, we are dedicated to providing content that accurately reflects the teachings of the Bhagavad Gita. While our interactive guidance is generated by Artificial Intelligence, all static content (such as blog posts, articles, and core page descriptions) is reviewed and curated by human editors who have a deep respect for and understanding of Vedic philosophy.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-bold mb-4 text-foreground">Content Generation & AI</h2>
          <p>
            The dynamic answers provided in the 'Ask' section are generated in real-time by a Large Language Model. To ensure quality, we have implemented strict system prompts that instruct the AI to:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>Base its advice purely on the verses and philosophy of the Bhagavad Gita.</li>
            <li>Maintain an empathetic, objective, and uplifting tone.</li>
            <li>Avoid making medical, financial, or professional psychological diagnoses.</li>
            <li>Refrain from engaging in contemporary political debates or sectarian controversies.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-bold mb-4 text-foreground">Updates and Corrections</h2>
          <p>
            If we discover that our AI system is consistently misinterpreting a specific philosophical concept or generating inappropriate responses, we will promptly update our underlying prompt architecture. If you notice any concerning output, please contact us at gitaguidanceweb@gmail.com.
          </p>
        </section>
        
        <section>
          <h2 className="font-serif text-2xl font-bold mb-4 text-foreground">Third-Party Links</h2>
          <p>
            Our website may contain links to external translations, commentaries, or resources. We select these links based on their general reputation for authenticity (e.g., standard translations by recognized scholars), but we are not responsible for the content of external sites.
          </p>
        </section>
      </div>
    </main>
  );
}
