import React from "react";
import Link from "next/link";
import { BookOpen } from "lucide-react";

export default function TermsOfServicePage() {
  return (
    <main className="flex-1 overflow-hidden relative py-20 px-4">
      {/* Background glow effects */}
      <div className="absolute top-0 right-1/2 translate-x-1/2 w-[800px] h-[600px] bg-primary/10 rounded-full blur-[120px] pointer-events-none" />

      <div className="max-w-4xl mx-auto relative z-10 glass p-8 md:p-12 rounded-3xl border border-white/5 shadow-lg">
        <div className="mb-10 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary mb-6">
            <BookOpen className="w-5 h-5" />
            <span>Legal</span>
          </div>
          <h1 className="font-serif text-4xl md:text-5xl font-bold mb-4 text-foreground">
            Terms of Service
          </h1>
          <p className="text-foreground/60 text-lg">
            Last Updated: July 2026
          </p>
        </div>

        <div className="space-y-8 text-foreground/80 leading-relaxed text-lg">
          <p>
            Welcome to Gita Guidance. By accessing or using our website, you agree to be bound by these Terms of Service and our Privacy Policy.
          </p>

          <h2 className="text-2xl font-serif font-bold text-foreground mt-8 mb-4">1. Description of Service</h2>
          <p>
            Gita Guidance is an AI-powered spiritual companion that provides responses and guidance based on the philosophical teachings of the Bhagavad Gita. The platform is designed for educational, spiritual, and entertainment purposes only.
          </p>

          <h2 className="text-2xl font-serif font-bold text-foreground mt-8 mb-4">2. Nature of AI-Generated Content</h2>
          <p>
            The guidance provided on this platform is generated by Artificial Intelligence (Large Language Models) trained to emulate the tone and wisdom of the Bhagavad Gita. 
            <strong> Disclaimer:</strong> This content does not constitute professional psychological, medical, legal, or financial advice. The Gita Guidance Team is not liable for any actions taken based on the AI-generated responses.
          </p>

          <h2 className="text-2xl font-serif font-bold text-foreground mt-8 mb-4">3. User Conduct</h2>
          <p>
            You agree to use the service only for lawful purposes. You must not:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-2">
            <li>Attempt to abuse, exploit, or maliciously manipulate the AI engine.</li>
            <li>Use the platform to generate harmful, illegal, or highly offensive content.</li>
            <li>Attempt to breach the security of the application or access other users' private journal entries.</li>
          </ul>

          <h2 className="text-2xl font-serif font-bold text-foreground mt-8 mb-4">4. Account Responsibilities</h2>
          <p>
            If you create an account to use the journaling features, you are responsible for maintaining the security of your account credentials. You must immediately notify us of any unauthorized uses of your account.
          </p>

          <h2 className="text-2xl font-serif font-bold text-foreground mt-8 mb-4">5. Modifications to the Service</h2>
          <p>
            We reserve the right to modify or discontinue, temporarily or permanently, the service (or any part thereof) with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the service.
          </p>

          <h2 className="text-2xl font-serif font-bold text-foreground mt-8 mb-4">6. Contact Information</h2>
          <p>
            For any questions regarding these Terms of Service, please contact us at <a href="mailto:gitaguidanceweb@gmail.com" className="text-primary hover:underline">gitaguidanceweb@gmail.com</a>.
          </p>
        </div>
      </div>
    </main>
  );
}
